interface Content {
  title: string
  body: string
  author: string
  date: string
  tags:string[]
}
const dummyContent: Content[] = [
  {
    title: '5 Tips Menulis Artikel SEO Friendly',
    tags: ['SEO', 'menulis', 'blogging'],
    body: 'Artikel SEO friendly adalah artikel yang ditulis dengan memperhatikan kriteria mesin pencari seperti Google. Tujuannya adalah agar artikel bisa mendapatkan peringkat yang baik di halaman hasil pencarian (SERP) dan mendatangkan banyak pengunjung. Artikel SEO friendly tidak hanya bermanfaat bagi mesin pencari, tetapi juga bagi pembaca. Artikel yang SEO friendly harus informatif, relevan, dan mudah dibaca. Berikut adalah 5 tips menulis artikel SEO friendly yang bisa Anda terapkan:',
    author: 'Rizki Pratama',
    date: '2023-07-15',
  },
  {
    title: 'Cara Membuat Logo dengan Photoshop',
    tags: ['desain', 'logo', 'photoshop'],
    body: 'Logo adalah simbol grafis yang merepresentasikan sebuah merek, perusahaan, atau organisasi. Logo harus memiliki desain yang unik, menarik, dan mudah diingat. Salah satu software yang bisa digunakan untuk membuat logo adalah Photoshop. Photoshop adalah software pengolah gambar yang memiliki banyak fitur dan alat yang bisa membantu Anda membuat logo sesuai dengan keinginan Anda. Berikut adalah cara membuat logo dengan Photoshop:',
    author: 'Rizki Pratama',
    date: '2023-07-16',
  },
  {
    title: 'Review Buku The Power of Habit',
    tags: ['buku', 'review', 'kebiasaan'],
    body: 'The Power of Habit adalah buku yang ditulis oleh Charles Duhigg, seorang jurnalis investigatif yang menguak rahasia di balik kebiasaan manusia. Buku ini menjelaskan bagaimana kebiasaan terbentuk, bagaimana kebiasaan mempengaruhi perilaku kita, dan bagaimana kita bisa mengubah kebiasaan yang tidak diinginkan menjadi kebiasaan yang positif. Buku ini juga memberikan banyak contoh nyata dari orang-orang, perusahaan, dan organisasi yang berhasil mengubah kebiasaan mereka dan meraih kesuksesan. Buku ini sangat menarik dan bermanfaat bagi siapa saja yang ingin memahami dan mengendalikan kebiasaan mereka.',
    author: 'Rizki Pratama',
    date: '2023-07-17',
  },
  {
    title: 'Cara Mengurus Perizinan Usaha Online',
    tags: ['perizinan', 'usaha', 'online'],
    body: 'Perizinan usaha adalah salah satu hal yang penting bagi para pelaku usaha. Perizinan usaha adalah dokumen resmi yang dikeluarkan oleh pemerintah yang memberikan izin kepada seseorang atau badan usaha untuk menjalankan kegiatan usahanya. Perizinan usaha bisa berupa SIUP (Surat Izin Usaha Perdagangan), TDP (Tanda Daftar Perusahaan), NPWP (Nomor Pokok Wajib Pajak), dan lain-lain. Perizinan usaha bisa diurus secara offline maupun online. Cara mengurus perizinan usaha online adalah sebagai berikut:',
    author: 'Dewi Sartika',
    date: '2023-07-15',
  },
  {
    title: 'Tips Memilih Nama Domain untuk Bisnis',
    tags: ['domain', 'bisnis', 'tips'],
    body: 'Nama domain adalah alamat website yang digunakan untuk mengidentifikasi sebuah situs di internet. Nama domain adalah salah satu faktor yang mempengaruhi kesuksesan sebuah bisnis online. Nama domain harus mampu mencerminkan identitas, visi, dan misi bisnis Anda. Nama domain juga harus mudah diingat, mudah dieja, dan mudah diketik. Berikut adalah beberapa tips memilih nama domain untuk bisnis Anda:',
    author: 'Dewi Sartika',
    date: '2023-07-16',
  },
  {
    title: 'Keuntungan Menggunakan WordPress untuk Website',
    tags: ['wordpress', 'website', 'keuntungan'],
    body: 'WordPress adalah salah satu platform pembuatan website yang paling populer di dunia. WordPress adalah software open source yang bisa digunakan secara gratis oleh siapa saja. WordPress memiliki banyak fitur dan fungsi yang bisa membantu Anda membuat website sesuai dengan kebutuhan Anda. WordPress juga memiliki banyak tema dan plugin yang bisa menambahkan fitur dan fungsi tambahan pada website Anda. Berikut adalah beberapa keuntungan menggunakan WordPress untuk website Anda:',
    author: 'Dewi Sartika',
    date: '2023-07-17',
  },
  {
    title: 'Belajar React Native dari Nol hingga Mahir',
    tags: ['react native', 'mobile', 'belajar'],
    body: 'React Native adalah framework yang memungkinkan Anda membuat aplikasi mobile yang berjalan di berbagai platform, seperti Android dan iOS, dengan menggunakan bahasa pemrograman JavaScript. React Native adalah salah satu framework yang paling populer dan diminati oleh para developer mobile saat ini. React Native memiliki banyak kelebihan, seperti performa yang tinggi, kemudahan pengembangan, dan dukungan komunitas yang besar. Jika Anda ingin belajar React Native dari nol hingga mahir, berikut adalah langkah-langkah yang bisa Anda ikuti:',
    author: 'Andi Setiawan',
    date: '2023-07-15',
  },
  {
    title: 'Mengenal Firebase sebagai Backend as a Service',
    tags: ['firebase', 'backend', 'baas'],
    body: 'Firebase adalah platform yang menyediakan berbagai layanan backend untuk aplikasi web dan mobile, seperti database, authentication, storage, hosting, analytics, dan lain-lain. Firebase adalah salah satu contoh dari Backend as a Service (BaaS), yaitu layanan yang menyediakan backend secara lengkap dan siap pakai tanpa perlu mengurus infrastruktur dan pemrograman backend. Firebase memiliki banyak keuntungan, seperti kemudahan penggunaan, skalabilitas yang tinggi, integrasi dengan Google Cloud Platform, dan biaya yang fleksibel. Berikut adalah beberapa layanan Firebase yang bisa Anda gunakan untuk aplikasi Anda:',
    author: 'Andi Setiawan',
    date: '2023-07-16',
  },
  {
    title: 'Tutorial Membuat Aplikasi Chat dengan Socket.io',
    tags: ['socket.io', 'chat', 'tutorial'],
    body: 'Aplikasi chat adalah salah satu jenis aplikasi yang banyak digunakan oleh pengguna internet. Aplikasi chat memungkinkan pengguna untuk berkomunikasi secara real-time dengan pengguna lain melalui teks, suara, atau video. Salah satu teknologi yang bisa digunakan untuk membuat aplikasi chat adalah Socket.io. Socket.io adalah library JavaScript yang memfasilitasi komunikasi antara client dan server melalui WebSocket. WebSocket adalah protokol yang memungkinkan pertukaran data secara dua arah dan persisten antara client dan server. Berikut adalah tutorial membuat aplikasi chat dengan Socket.io:',
    author: 'Andi Setiawan',
    date: '2023-07-17',
  },
  {
    title: 'Resep Kue Lapis Legit Enak dan Mudah',
    tags: ['kue', 'lapis legit', 'resep'],
    body: 'Kue lapis legit adalah salah satu kue khas Indonesia yang memiliki tekstur lembut dan rasa manis. Kue ini terdiri dari banyak lapisan tipis yang dibuat dari adonan tepung, telur, gula, mentega, dan rempah-rempah. Kue lapis legit biasanya disajikan saat hari raya atau acara spesial lainnya. Membuat kue lapis legit memang membutuhkan kesabaran dan ketelitian, tetapi hasilnya pasti memuaskan. Berikut adalah resep kue lapis legit enak dan mudah yang bisa Anda coba di rumah:',
    author: 'Siti Nurhaliza',
    date: '2023-07-15',
  },
  {
    title: 'Cara Membuat Es Krim Rumahan Tanpa Mesin',
    tags: ['es krim', 'rumahan', 'cara membuat'],
    body: 'Es krim adalah salah satu makanan penutup yang disukai oleh banyak orang. Es krim memiliki tekstur lembut dan dingin yang menyegarkan. Es krim bisa dibuat dengan berbagai rasa, seperti cokelat, vanila, stroberi, durian, dan lain-lain. Es krim biasanya dibuat dengan menggunakan mesin pembuat es krim yang bisa menghasilkan tekstur yang halus dan rata. Namun, Anda juga bisa membuat es krim rumahan tanpa mesin dengan cara yang sederhana. Berikut adalah cara membuat es krim rumahan tanpa mesin:',
    author: 'Siti Nurhaliza',
    date: '2023-07-16',
  },
  {
    title: 'Tips Menjaga Kesehatan Kulit Wajah dari Paparan Sinar Matahari',
    tags: ['kulit wajah', 'sinar matahari', 'tips'],
    body: 'Sinar matahari adalah salah satu sumber vitamin D yang baik bagi tubuh. Namun, sinar matahari juga bisa berbahaya bagi kulit wajah jika terpapar secara berlebihan. Sinar matahari bisa menyebabkan kulit wajah menjadi kusam, kering, berjerawat, bahkan berisiko terkena kanker kulit. Oleh karena itu, Anda perlu menjaga kesehatan kulit wajah dari paparan sinar matahari dengan cara-cara berikut ini:',
    author: 'Siti Nurhaliza',
    date: '2023-07-17',
  },
  {
    title: 'Ulasan Film Spider-Man No Way Home (Spoiler Free)',
    tags: ['film', 'spider-man', 'ulasan'],
    body: 'Spider-Man No Way Home adalah film superhero yang merupakan sekuel dari Spider-Man Homecoming dan Spider-Man Far From Home. Film ini juga merupakan bagian dari Marvel Cinematic Universe (MCU) yang menghubungkan cerita Spider-Man dengan karakter-karakter lain dari Marvel. Film ini dibintangi oleh Tom Holland sebagai Peter Parker/Spider-Man, Zendaya sebagai MJ, Benedict Cumberbatch sebagai Doctor Strange, dan lain-lain. Film ini menceritakan tentang petualangan Spider-Man yang harus menghadapi konsekuensi dari terbongkarnya identitasnya sebagai Peter Parker di akhir film sebelumnya. Spider-Man kemudian meminta bantuan Doctor Strange untuk mengubah realitas agar identitasnya kembali rahasia, namun hal ini menimbulkan masalah yang lebih besar. Berikut adalah ulasan film Spider-Man No Way Home tanpa spoiler:',
    author: 'Budi Santoso',
    date: '2023-07-15',
  },
  {
    title: 'Daftar Film Marvel yang Akan Rilis di Tahun 2022',
    tags: ['film', 'marvel', 'daftar'],
    body: 'Marvel adalah salah satu studio film yang paling sukses dan populer di dunia. Marvel telah menghasilkan banyak film superhero yang menjadi favorit banyak orang, seperti Avengers, Iron Man, Captain America, Thor, Black Panther, dan lain-lain. Marvel juga terkenal dengan Marvel Cinematic Universe (MCU), yaitu sebuah alam semesta fiksi yang menghubungkan semua film Marvel dalam satu cerita besar. Marvel masih memiliki banyak proyek film yang akan dirilis di tahun 2022, baik yang merupakan sekuel maupun yang merupakan film baru. Berikut adalah daftar film Marvel yang akan rilis di tahun 2022:',
    author: 'Budi Santoso',
    date: '2023-07-16',
  },
  {
    title: 'Cara Menonton Film di Netflix Gratis Selama Sebulan Penuh',
    tags: ['film', 'netflix', 'gratis'],
    body: 'Netflix adalah salah satu platform streaming film dan serial TV online yang paling populer di dunia. Netflix memiliki banyak konten yang berkualitas dan bervariasi, mulai dari drama, komedi, aksi, horor, dokumenter, animasi, hingga konten original Netflix sendiri. Netflix biasanya membutuhkan biaya berlangganan bulanan untuk bisa menikmati semua kontennya. Namun, ada cara untuk menonton film di Netflix gratis selama sebulan penuh tanpa harus membayar biaya berlangganan. Berikut adalah cara menonton film di Netflix gratis selama sebulan penuh:',
    author: 'Budi Santoso',
    date: '2023-07-17',
  },
  {
    title: 'Cara Mengatur Keuangan Rumah Tangga dengan Baik',
    tags: ['keuangan', 'rumah tangga', 'cara mengatur'],
    body: 'Keuangan rumah tangga adalah salah satu hal yang penting bagi keluarga. Keuangan rumah tangga berkaitan dengan pengelolaan uang yang digunakan untuk memenuhi kebutuhan sehari-hari, menabung, berinvestasi, dan lain-lain. Keuangan rumah tangga yang baik akan membantu keluarga untuk hidup lebih sejahtera, nyaman, dan aman. Keuangan rumah tangga yang buruk akan menyebabkan keluarga mengalami masalah finansial, seperti utang, kekurangan uang, stres, dan konflik. Berikut adalah cara mengatur keuangan rumah tangga dengan baik:',
    author: 'Rina Wati',
    date: '2023-07-15',
  },
  {
    title: 'Tips Memilih Asuransi Kesehatan yang Tepat untuk Keluarga',
    tags: ['asuransi', 'kesehatan', 'tips memilih'],
    body: 'Asuransi kesehatan adalah salah satu produk asuransi yang memberikan perlindungan finansial bagi Anda dan keluarga jika mengalami sakit atau kecelakaan. Asuransi kesehatan akan membayar biaya pengobatan atau perawatan kesehatan sesuai dengan ketentuan polis asuransi. Asuransi kesehatan sangat bermanfaat bagi Anda dan keluarga karena bisa mengurangi beban biaya kesehatan yang bisa sangat mahal. Namun, tidak semua asuransi kesehatan cocok untuk Anda dan keluarga. Anda perlu memilih asuransi kesehatan yang tepat sesuai dengan kebutuhan, anggaran, dan preferensi Anda. Berikut adalah tips memilih asuransi kesehatan yang tepat untuk keluarga Anda:',
    author: 'Rina Wati',
    date: '2023-07-16',
  },
  {
    title: 'Ide Bisnis Rumahan yang Menguntungkan dan Mudah Dijalankan',
    tags: ['bisnis', 'rumahan', 'ide'],
    body: 'Bisnis rumahan adalah salah satu jenis bisnis yang bisa dilakukan di rumah dengan modal yang relatif kecil. Bisnis rumahan cocok bagi Anda yang ingin memiliki penghasilan tambahan, tidak ingin terikat dengan jam kerja, atau ingin mengembangkan bakat dan hobi Anda. Bisnis rumahan juga bisa menjadi sumber pendapatan utama jika dikelola dengan baik. Ada banyak ide bisnis rumahan yang bisa Anda coba, baik yang berbasis online maupun offline. Berikut adalah beberapa ide bisnis rumahan yang menguntungkan dan mudah dijalankan:',
    author: 'Rina Wati',
    date: '2023-07-17',
  },
  {
    title: 'Cara Bermain Gitar untuk Pemula dalam 30 Hari',
    tags: ['gitar', 'pemula', 'cara bermain'],
    body: 'Gitar adalah salah satu alat musik yang banyak digemari oleh orang-orang. Gitar memiliki suara yang merdu dan bisa dimainkan untuk berbagai genre musik, seperti pop, rock, jazz, blues, dan lain-lain. Gitar juga bisa dimainkan secara solo maupun bersama dengan alat musik lainnya. Gitar adalah alat musik yang cukup mudah dipelajari, bahkan bagi pemula sekalipun. Anda bisa belajar bermain gitar dengan cepat dan mudah jika Anda memiliki metode yang tepat. Berikut adalah cara bermain gitar untuk pemula dalam 30 hari:',
    author: 'Adi Prasetyo',
    date: '2023-07-15',
  },
  {
    title: 'Daftar Lagu Gampang Dipelajari untuk Pemula',
    tags: ['gitar', 'lagu', 'daftar'],
    body: 'Belajar bermain gitar tidak harus selalu dengan lagu-lagu yang sulit dan kompleks. Anda bisa belajar bermain gitar dengan lagu-lagu yang gampang dipelajari, tetapi tetap enak didengar. Lagu-lagu gampang dipelajari biasanya memiliki chord-chord dasar yang mudah dihafal dan ritme yang sederhana. Lagu-lagu gampang dipelajari juga bisa membantu Anda untuk meningkatkan keterampilan bermain gitar Anda secara bertahap. Berikut adalah daftar lagu gampang dipelajari untuk pemula:',
    author: 'Adi Prasetyo',
    date: '2023-07-16',
  },
  {
    title: 'Review Gitar Akustik yang Bagus dan Murah',
    tags: ['gitar', 'akustik', 'review'],
    body: 'Gitar akustik adalah jenis gitar yang menghasilkan suara akustik tanpa menggunakan listrik. Gitar akustik memiliki bentuk yang besar dan berongga di bagian tengahnya. Gitar akustik cocok untuk dimainkan untuk genre musik seperti folk, country, pop, dan lain-lain. Gitar akustik juga cocok untuk pemula karena memiliki senar yang lebih lembut dan nyaman dijari. Jika Anda ingin membeli gitar akustik, Anda tidak perlu mengeluarkan banyak uang. Ada banyak gitar akustik yang bagus dan murah yang bisa Anda pilih. Berikut adalah review gitar akustik yang bagus dan murah:',
    author: 'Adi Prasetyo',
    date: '2023-07-17',
  },
  {
    title: 'Cara Membuat Hiasan Dinding dari Kertas Origami',
    tags: ['hiasan dinding', 'kertas origami', 'cara membuat'],
    body: 'Hiasan dinding adalah salah satu elemen dekorasi yang bisa membuat ruangan menjadi lebih cantik dan menarik. Hiasan dinding bisa dibuat dari berbagai bahan, seperti kayu, kain, logam, atau kertas. Salah satu bahan yang bisa digunakan untuk membuat hiasan dinding adalah kertas origami. Kertas origami adalah kertas berwarna-warni yang bisa dilipat menjadi berbagai bentuk, seperti bunga, kupu-kupu, burung, atau hewan lainnya. Kertas origami bisa dibeli di toko buku atau toko kertas dengan harga yang murah. Berikut adalah cara membuat hiasan dinding dari kertas origami:',
    author: 'Lia Anggraini',
    date: '2023-07-15',
  },
  {
    title: 'Inspirasi Desain Interior Minimalis untuk Kamar Tidur',
    tags: ['desain interior', 'minimalis', 'inspirasi'],
    body: 'Desain interior minimalis adalah salah satu gaya desain yang populer saat ini. Desain interior minimalis mengusung konsep simpel, fungsional, dan efisien. Desain interior minimalis cocok untuk ruangan yang kecil atau terbatas, seperti kamar tidur. Desain interior minimalis bisa membuat kamar tidur menjadi lebih luas, nyaman, dan rapi. Berikut adalah beberapa inspirasi desain interior minimalis untuk kamar tidur Anda:',
    author: 'Lia Anggraini',
    date: '2023-07-16',
  },
  {
    title: 'Tips Menata Rumah Sempit Menjadi Luas dan Nyaman',
    tags: ['rumah', 'sempit', 'tips menata'],
    body: 'Rumah sempit bukanlah halangan untuk memiliki rumah yang luas dan nyaman. Anda bisa menata rumah sempit Anda dengan cara-cara yang cerdas dan kreatif. Anda bisa memanfaatkan setiap sudut dan ruang kosong di rumah Anda untuk menyimpan barang-barang atau menambahkan dekorasi. Anda juga bisa memilih warna, pencahayaan, dan furnitur yang sesuai untuk membuat rumah Anda terlihat lebih lapang. Berikut adalah beberapa tips menata rumah sempit menjadi luas dan nyaman:',
    author: 'Lia Anggraini',
    date: '2023-07-17',
  },
]
export default dummyContent
